apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-init-scripts
data:
  init.sql: |
    CREATE DATABASE demo;
    GO
    USE demo;
    CREATE TABLE greetings(id INT PRIMARY KEY, message NVARCHAR(100));
    INSERT INTO greetings VALUES (1, 'Hello world');
    GO
